import React, { Component } from 'react'
import Box from 'grommet/components/Box'
import Button from 'grommet/components/Button'
import Heading from 'grommet/components/Heading'
import Layer from 'grommet/components/Layer'
import Image from 'grommet/components/Image'

export default class CometInitModal extends Component {
    render() {
        return (
            <Layer onClose={() => {
                this.props.toggleCometInitModal()
                this.props.toggleCometSuccessModal()}}>
                <Box
                    align='center'
                    pad='small'>
                    <Image
                        size='small'
                        src='public/img/ceki.png' />
                    <Box
                        align='center'
                        pad='small'>
                        <Heading
                            tag='h4'
                            align='center'
                            strong
                            margin='none'>
                            Your transaction code is <i>755130</i>
                        </Heading>
                        <Heading
                            tag='h4'
                            align='center'
                            strong
                            margin='none'>
                            Give this code to your customer and scan the barcode generated by your customer's COMET app.
                        </Heading>
                    </Box>
                    <Box
                        align='center'
                        pad='medium'>
                        <Heading
                            tag='h5'
                            align='center'
                            margin='none'>
                            © TEAM COMET 2017
                        </Heading>
                    </Box>
                </Box>
            </Layer>
        )
    }
}